version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: rental-postgres
    environment:
      POSTGRES_DB: rental_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: challenge@123
    ports:
      - "5432:5432" 
    volumes:
      - postgres-data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rental-rabbitmq
    ports:
      - "5672:5672" 
      - "15672:15672"

volumes:
  postgres-data: